### ISSUE TITLE
Create an Electrification Page for Landlords

### ISSUE THREAD

**Issue by vkoves** [chihacknight/state-by-state-decarbonization#11]
Let's create a page targeted specifically towards landlords giving them some recommendations on electrification and why it would benefit them (such as through costs savings over the long-term). We can use the [Rewiring America Electrify Home Guide](https://www.rewiringamerica.org/electrify-home-guide) as a starting point.

**Comment by vkoves** [comment]
@derekeder - for when you get back, is this still something we want to do? I'm assigning this to you just to confirm

**Comment by derekeder** [comment]
same as #12, lets close for now and revisit once we have our primary data pages complete
