### ISSUE TITLE
Create an Electrification Page for Renters

### ISSUE THREAD

**Issue by vkoves** [chihacknight/state-by-state-decarbonization#12]
Let's create a page targeted towards renters to help them both electrify items they control (like a vehicle) and to give them tools and suggestions to advocate for their landlord to get electric appliances. As a tenant myself, even a nice pamphlet I could hand to my landlord would be super helpful.

**Comment by vkoves** [comment]
@derekeder - for when you get back, is this still something we want to do? I'm assigning this to you just to confirm

**Comment by derekeder** [comment]
lets close for now and revisit once we have our primary data pages complete
