### ISSUE TITLE
Add Homepage Total US Pollution Chart with Projection to 0 by 2050

### ISSUE THREAD

**Issue by derekeder** [chihacknight/state-by-state-decarbonization#17]
Using `Recharts` create a new Component chart that shows current US emissions and what we need to do to get to 0 by 2050:

Example spreadsheet and chart: https://docs.google.com/spreadsheets/d/1QIWu0BSWCW2AgrJilhcsPA20jTdDjxqNJGoMx9c8-Iw/edit#gid=0

<img width="840" alt="Screen Shot 2022-03-08 at 4 46 55 PM" src="https://user-images.githubusercontent.com/919583/157338853-a81d609d-8506-414f-9ac6-9d98e11b7109.png">

Steps

1. Create a function to generate the projected emissions from a given year until 2050 to get to zero
2. Create a new component based on `SimpleAreaChart` with 2 series (actual + projection) https://recharts.org/en-US/examples/SimpleAreaChart 
3. Add the component to the home page and pass in US total emissions
4. Add the component to the state detail page and pass in that state's emissions

**Comment by hkier** [comment]
As I expect the emissions data to lag behind the current year (current data ends 2018 and we are in 2022), how should the "missing data" be handled in the SimpleAreaChart.  Do we want a gap?  Do we project from the last year in which we have data?  Something else?

**Comment by derekeder** [comment]
@hkier the chart should show the projection based on the last year of data we have. It'll be on us to find data up to 2022 and handle that in a separate issue we already have open https://github.com/chihacknight/state-by-state-decarbonization/issues/10

**Comment by hkier** [comment]
The way the component is currently written, the historical data ends in 2018.  2019-2021 have no data.  The projection starts at 2022 using the historical data from the last year of historical data as a starting point.  It is not obvious from the area graph there are years with missing data.  

The code is written in such a way, it does not matter when the historical data ends.  It is also written so we can add "estimated data" for the missing data or just ignore the gap.

I assume even though we might be missing data, we do not want the graph to show a gap.
