### ISSUE TITLE
Create stacked bar chart for one year

### ISSUE THREAD

**Issue by derekeder** [chihacknight/state-by-state-decarbonization#18]
Create a new `Recharts` component for a single stacked bar so we can start generating charts like this:

<img width="402" alt="Screen Shot 2022-03-08 at 4 55 37 PM" src="https://user-images.githubusercontent.com/919583/157339746-52dc3a7f-8b15-4b67-a37d-f86ed06565d5.png">

We can then reuse this component on the Home page:

<img width="1016" alt="Screen Shot 2022-03-08 at 4 56 24 PM" src="https://user-images.githubusercontent.com/919583/157339828-0cf03272-5254-4ce7-a62f-d7da8f76f646.png">

and throughout the state detail page:

<img width="858" alt="Screen Shot 2022-03-08 at 4 56 48 PM" src="https://user-images.githubusercontent.com/919583/157339912-b2a53dba-c411-4656-8e36-f1aa0f89c0f2.png">
<img width="832" alt="Screen Shot 2022-03-08 at 4 56 57 PM" src="https://user-images.githubusercontent.com/919583/157339924-b71b9b61-ab66-4587-a537-089155ee9e61.png">

We can use this as a starting example: https://recharts.org/en-US/examples/StackedBarChart

**Comment by hkier** [comment]
I will give this a shot.  Please assign this issue to me.
