### ISSUE TITLE
Home page layout

### ISSUE THREAD

**Issue by derekeder** [chihacknight/state-by-state-decarbonization#19]
Going off of our wireframe, stub out the content and chart / image placeholders for the home page: https://app.moqups.com/pcSQvUMmsyAa1SN58KaKg1EKuYRs8iRX/view/page/a68639957

<img width="1021" alt="Screen Shot 2022-03-08 at 4 59 41 PM" src="https://user-images.githubusercontent.com/919583/157340234-c1fd1fb3-ff74-439e-b13b-f6c692c0950f.png">

**Comment by vkoves** [comment]
This is pretty simple compared to #20 so I can also grab it, especially since it doesn't contain include the graphs it should be like 30 minutes of work!
