### ISSUE TITLE
Get data on number of cars / vehicles in each State

### ISSUE THREAD

**Issue by derekeder** [chihacknight/state-by-state-decarbonization#22]
Similar to #21, we need the total count of motor vehicles in each State.

Bonus points for number of EV's vs combustion engine

Data should be collected in a Google Sheet with one row for each State

**Comment by derekeder** [comment]
Shelby Barron will be taking this one on.

Possible data sources:
- AAA
- insurance stats
- https://www.statista.com/statistics/196036/number-of-registered-automobiles-in-illinois/
- US census - aggregate number of cars per commuter: https://api.census.gov/data/2010/acs/acs1/groups/B08015.html

**Comment by scbarron** [comment]
The most recent/comprehensive source I could find was from the federal highway administration (fhwa) 
Can pull CSV of 2020 data [here](https://www.fhwa.dot.gov/policyinformation/statistics/2017/mv1.cfm)
Also available in my [google doc ](https://docs.google.com/spreadsheets/d/1N03Y54xjG0dXl-mQEv69y7qA6RDow-XOa671jXBuZTo/edit?usp=sharing)
Notes:

**Comment by scbarron** [comment]
EVs Per State, 2020
Can pull CSV of 2020 data [here](https://afdc.energy.gov/data/10962)
Also available in my [google doc](https://docs.google.com/spreadsheets/d/1N03Y54xjG0dXl-mQEv69y7qA6RDow-XOa671jXBuZTo/edit?usp=sharing)                                                                                                                                                                                                                                                           
Notes:                                                                                                                                
The data was last updated in June of 2021 and represented all registered EVs in the US as of December 31st, 2020.                                                                                                                                
Note that this data includes Battery-EVs only and does not account for any hybrids or PHEVs.

**Comment by derekeder** [comment]
@scbarron this is great! In addition to getting the data import started in #32, it would be great to know what the % of new sales are EVs vs standard cars for each state. not critical, but following up on your research about availability of charging stations and EV subsidies per state would also be helpful.

**Comment by scbarron** [comment]
3/29 update: General data is available (see below). [MVbyState_RawData2020](https://docs.google.com/spreadsheets/d/1N03Y54xjG0dXl-mQEv69y7qA6RDow-XOa671jXBuZTo/edit#gid=1465868077),[EVbyState_RawData2020](https://docs.google.com/spreadsheets/d/1N03Y54xjG0dXl-mQEv69y7qA6RDow-XOa671jXBuZTo/edit#gid=2092834002)
% of EVs per state vs. standard cars pending. If we make the assumption that the # of EV registrations per state from AFDC is "Cars_Private", we could arrive at these percentages easily & include the EV data as a column in the MV by State tab.
