### ISSUE TITLE
Get data on number of coal and gas power plants in each State

### ISSUE THREAD

**Issue by derekeder** [chihacknight/state-by-state-decarbonization#23]
Similar to #21 and #22 we also want to get a count of the number of coal plants and gas power plants in a State.

Some starting places:

- https://en.wikipedia.org/wiki/List_of_power_stations_in_Illinois#Natural_gas
- https://www.gem.wiki/Category:Existing_coal_plants_in_Illinois

Data should be collected in a Google Sheet with one row for each State

**Comment by nsteins** [comment]
Here is a groupby count of all plants for each fuel category from the eGrid 2020 data set - which covers all plants over 25MW

https://docs.google.com/spreadsheets/d/10htOQRLiCxIaZAvkNbXLSpVyyQl5TFRJ0eiLAACaCbg/edit?usp=sharing

**Comment by nsteins** [comment]
eGrid also contains information on generation and emissions by plant: https://www.epa.gov/egrid

**Comment by derekeder** [comment]
David Silverman will take this one on.

Possible sources:
- DOE
- IL CUB
- https://api.census.gov/data/2010/acs/acs1/groups/B08015.html
- https://www.eia.gov/electricity/annual/html/epa_04_01.html

**Comment by derekeder** [comment]
Joyce will take this on (Derek to assist)

**Comment by joyceohiri** [comment]
Coal production and number of coal mines in Illinois (2020):
[CoalProduction_NumberofMines_2020.xlsx](https://github.com/chihacknight/state-by-state-decarbonization/files/8258456/CoalProduction_NumberofMines_2020.xlsx)

**Comment by derekeder** [comment]
@joyceohiri nice - these are good sources for coal mines. we're less concerned about the mines and more on the power plants that use the coal, as well as the natural gas plants.

**Comment by derekeder** [comment]
Promising data source from the EPA: https://www.epa.gov/airmarkets/power-plants-and-neighboring-communities#mapping

**Comment by joyceohiri** [comment]
Thanks for sharing! Here's the data from that source
[power_plants_and_communities.xlsx](https://github.com/chihacknight/state-by-state-decarbonization/files/8376650/power_plants_and_communities.xlsx)
:

**Comment by joyceohiri** [comment]
[power_plants_and_communities.csv](https://github.com/chihacknight/state-by-state-decarbonization/files/8376686/power_plants_and_communities.csv)

**Comment by vkoves** [comment]
Great work, Joyce, thank you!

**Comment by derekeder** [comment]
@joyceohiri thanks - this looks to be what we need! I think the next step is to review the data and confirm it has everything we need. I put this in a google sheet for easier/shared access: https://docs.google.com/spreadsheets/d/17sBCD1prwzRsuA2oT-CA6VmOhEeB6Ao9m32B12EAPKs/edit#gid=737725675


based on what I see, we can use the `Plant state abbreviation` and `Plant primary coal/oil/gas/ other fossil fuel category` to organize these.

Joy - can you provide some additional context on where you got this data from and if there is any documentation on the meaning behind each of the columns?

**Comment by hkier** [comment]
Will look at the data to understand it and get ideas for bringing it into the website.

**Comment by derekeder** [comment]
this is done! moving on to data import
