### ISSUE TITLE
Remove Territories from SVG Map 

### ISSUE THREAD

**Issue by vkoves** [chihacknight/state-by-state-decarbonization#31]
We don't have emissions data for those (since they are not in the 50 states) so we should just remove them from map.

Also make sure there's no page being generated for Guam or other territories.

**Comment by nofurtherinformation** [comment]
Was multitasking a bit -- dropping this here:

https://gist.github.com/nofurtherinformation/ef709796f87db182abac46b8c450f3d8

**Comment by vkoves** [comment]
I actually don't think we use the SVG but use a big JSON file, sorry for the not specifying. I should be able to just remove the related territories pretty easily now that I think about it.
