### ISSUE TITLE
Import vehicle data into website

### ISSUE THREAD

**Issue by derekeder** [chihacknight/state-by-state-decarbonization#32]
With the data that @scbarron has collected for vehicles per state in [#22-comment](https://github.com/chihacknight/state-by-state-decarbonization/issues/22#issuecomment-1068579090), lets incorporate it into the data pipeline that @swatland610 set up. 

@joyceohiri is researching the power plants data #23 and is interested in learning more about the data import process.

**Comment by scbarron** [comment]
3/329 update - haven't been able to get docker on my work computer, so stalled on this. I formatted the data in the google sheets to make it easier to import see below
[MVbyState_RawData2020
](https://docs.google.com/spreadsheets/d/1N03Y54xjG0dXl-mQEv69y7qA6RDow-XOa671jXBuZTo/edit#gid=1465868077)
[EVbyState_RawData2020](https://docs.google.com/spreadsheets/d/1N03Y54xjG0dXl-mQEv69y7qA6RDow-XOa671jXBuZTo/edit#gid=2092834002)

**Comment by nofurtherinformation** [comment]
Closed by #44
