### ISSUE TITLE
Upgrade recharts to 2.1.9

### ISSUE THREAD

**Issue by hkier** [chihacknight/state-by-state-decarbonization#41]
The current version of recharts does not properly display the area chart required for issue #17.  This problem is solved in version 2.1.9

**Comment by vkoves** [comment]
I should be able to open a quick PR for this tonight - I'm also tinkering with existing graphs for the #28 so I want to make sure they don't break on upgrade

**Comment by vkoves** [comment]
This will be done in PR #43
