### ISSUE TITLE
Make State Details Page Graph Sticky

### ISSUE THREAD

**Issue by vkoves** [chihacknight/state-by-state-decarbonization#46]
Make the graph order match the section order and make the graph sticky, using a scroll observer to update the graph based on where you are on the page.

**Comment by derekeder** [comment]
Per https://github.com/chihacknight/state-by-state-decarbonization/pull/40#issuecomment-1089040713 we'll need to come up with an alternative for mobile view. We will probably wind up making use of Bootstrap 4's visibility utilities: https://getbootstrap.com/docs/4.6/utilities/visibility/
